### ISSUE TITLE
Dies on changing localtime

### ISSUE THREAD

**Issue by fiddur** [aptalca/docker-digikam#5]
Starting up with suggested command leads to an error from a new localtime:

```
*** Running /etc/my_init.d/00_config.sh...
mv: cannot move '/etc/localtime.dpkg-new' to '/etc/localtime': Device or resource busy
*** /etc/my_init.d/00_config.sh failed with status 1

*** Killing all processes...
```

I tried giving it a rw localtime file with `…:/etc/localtime:rw` instead of `ro`, but I still get the above error message.

I'm quite new to docker, but it seems it doesn't handle replacing the file mounted on outside filesystem with mv…?

**Comment by aptalca** [comment]
Instead of the `-v /etc/localtime:/etc/localtime:ro` can you try using `-e TZ="America/New_York"` and see if that works?

You can change the timezone according to the list here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Let me know if that solves the issue and I'll update the documentation

Thanks

**Comment by fiddur** [comment]
Thanks!  The `-e` worked well.

**Comment by aptalca** [comment]
Great!
Could you let me know what platform you are using this on? So I can try and trouble shoot and update the docs
Thanks

**Comment by fiddur** [comment]
Debian Jessie, in Sweden.

**Comment by aptalca** [comment]
Thanks
